name: Add Artifact Link to PR

on:
  workflow_run:
    workflows: ['Build Firmware']
    types: [completed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get PR information'
        uses: stylesuxx/get-workflow-origin@v0.2.0
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: 'Comment Artifact Link'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            const repositoryName = context.payload.repository.full_name;
            const suiteId = context.payload.workflow_run.check_suite_id;
            const pullRequestId = context.payload.workflow_run.pull_requests[0].number;

            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            const artifactId = allArtifacts.data.artifacts[0].id;

            const archiveUrl = `https://github.com/${repositoryName}/suites/${suiteId}/artifacts/${artifactId}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestId,
              body: `[Here are the build results](${archiveUrl}) (Artifacts will only be retained for 90 days)`
            });
