name: Add Artifact Link to PR

on:
  workflow_run:
    workflows: ['Build Firmware']
    types: [completed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get PR information'
        uses: stylesuxx/get-workflow-origin@v1_8
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: 'Comment Artifact Link'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);

            // Find triggering PR
            const sourceWorkflowId = context.payload.workflow_run.id;
            const headSha = context.payload.workflow_run.head_sha;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const allPRs = await github.rest.pulls.list({
               owner,
               repo,
               open: true,
            });
            
            console.log(sourceWorkflowId, headSha);
            console.log(allPRs);
            
            const matchingPRs = allPRs.data.filter((pr) => {
              /*
              console.log(pr);
              console.log(pr.head);
              console.log(pr.base);
              */
              
              return (pr.head.sha === headSha);
            });

            // Post comment if matching PR has been found
            if(matchingPRs.length > 0) {
              const pr = matchingPRs[0];
              const pullRequestId = pr.number;

              const repositoryName = context.payload.repository.full_name;
              const suiteId = context.payload.workflow_run.check_suite_id;

              const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: context.payload.workflow_run.id,
              });
              const artifactId = allArtifacts.data.artifacts[0].id;

              const archiveUrl = `https://github.com/${repositoryName}/suites/${suiteId}/artifacts/${artifactId}`;
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: pullRequestId,
                body: `[Here are the build results](${archiveUrl}) (Artifacts will only be retained for 90 days)`
              });
            }
